export const jobs = [
  {
    id: 1,
    title: "Nurse",
    description:
      "Providing care to patients, administering medication, and collaborating with healthcare teams.",
    category: "Healthcare",
    location: "Freetown, Sierra Leone",
    salary: "Le 2,000,000 - Le 3,500,000",
    company: "Sierra Leone Health Services",
    postedDate: "2024-10-28",
    slug: "nurse",
  },
  {
    id: 2,
    title: "Primary School Teacher",
    description:
      "Teaching various subjects to primary school students and developing lesson plans.",
    category: "Education",
    location: "Bo, Sierra Leone",
    salary: "Le 1,500,000 - Le 2,500,000",
    company: "Bright Future Academy",
    postedDate: "2024-10-20",
    slug: "primary-school-teacher",
  },
  {
    id: 3,
    title: "Agricultural Extension Officer",
    description:
      "Advising farmers on best practices for sustainable agriculture and crop production.",
    category: "Agriculture and Food Production",
    location: "Kenema, Sierra Leone",
    salary: "Le 1,800,000 - Le 2,800,000",
    company: "Sierra Leone Agricultural Development",
    postedDate: "2024-10-15",
    slug: "agricultural-extension-officer",
  },
  {
    id: 4,
    title: "Small Business Consultant",
    description:
      "Assisting local businesses in developing strategies to grow and succeed in the market.",
    category: "Entrepreneurship and Small Business",
    location: "Makeni, Sierra Leone",
    salary: "Le 2,500,000 - Le 4,000,000",
    company: "Local Business Solutions",
    postedDate: "2024-10-10",
    slug: "small-business-consultant",
  },
  {
    id: 5,
    title: "Software Developer",
    description:
      "Designing and developing software applications to meet business needs.",
    category: "Information Technology",
    location: "Freetown, Sierra Leone",
    salary: "Le 3,000,000 - Le 5,000,000",
    company: "Tech Innovations SL",
    postedDate: "2024-10-05",
    slug: "software-developer",
  },
  {
    id: 6,
    title: "Project Coordinator",
    description:
      "Managing project activities for various NGOs, ensuring timely completion of goals.",
    category: "Non-Governmental Organizations (NGOs)",
    location: "Freetown, Sierra Leone",
    salary: "Le 2,200,000 - Le 3,500,000",
    company: "Helping Hands NGO",
    postedDate: "2024-09-28",
    slug: "project-coordinator",
  },
  {
    id: 7,
    title: "Tour Guide",
    description:
      "Leading tourists through historical sites and providing information about local culture.",
    category: "Hospitality and Tourism",
    location: "Bonthe, Sierra Leone",
    salary: "Le 1,200,000 - Le 2,000,000",
    company: "Explore Sierra Leone",
    postedDate: "2024-09-20",
    slug: "tour-guide",
  },
  {
    id: 8,
    title: "Administrative Assistant",
    description:
      "Providing administrative support to office personnel and managing communications.",
    category: "Administrative and Office Management",
    location: "Freetown, Sierra Leone",
    salary: "Le 1,000,000 - Le 1,800,000",
    company: "Sierra Leone Enterprises",
    postedDate: "2024-09-15",
    slug: "administrative-assistant",
  },
  {
    id: 9,
    title: "Legal Advisor",
    description:
      "Offering legal advice and representation to clients in various legal matters.",
    category: "Legal and Advocacy Services",
    location: "Bo, Sierra Leone",
    salary: "Le 3,000,000 - Le 4,500,000",
    company: "Justice for All",
    postedDate: "2024-09-10",
    slug: "legal-advisor",
  },
  {
    id: 10,
    title: "Graphic Designer",
    description:
      "Creating visual content for print and digital media to promote brands and products.",
    category: "Arts and Media",
    location: "Freetown, Sierra Leone",
    salary: "Le 1,800,000 - Le 3,000,000",
    company: "Creative Agency SL",
    postedDate: "2024-09-05",
    slug: "graphic-designer",
  },
];
