export const modules = [
  {
    id: 1,
    code: "SCM-1013",
    name: "Civic Education",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "civic-education",
  },
  {
    id: 2,
    code: "DFREN-224",
    name: "French Language 1",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "french-language-1",
  },
  {
    id: 3,
    code: "COMM-108",
    name: "Introduction to Communication & Study Skills",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "introduction-to-communication-study-skills",
  },
  {
    id: 4,
    code: "COMP-101",
    name: "Introduction to Computer Skills",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "introduction-to-computer-skills",
  },
  {
    id: 5,
    code: "CRET-101",
    name: "Creative & Innovation Studies",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "creative-innovation-studies",
  },
  {
    id: 6,
    code: "PROG-101",
    name: "Principles of Programming Logic & Design",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-1",
    slug: "principles-of-programming-logic-design",
  },

  // Year 1 Sem 2
  {
    id: 7,
    code: "COMP-102",
    name: "Introduction to Databases",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "introduction-to-databases",
  },
  {
    id: 8,
    code: "COMP-105",
    name: "Introduction to Data Communication",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "introduction-to-data-communication",
  },
  {
    id: 9,
    code: "MATH-108",
    name: "Computerized Mathematics",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "computerized-mathematics",
  },
  {
    id: 10,
    code: "COMP-109",
    name: "Introduction to Computer Hardware",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "introduction-to-computer-hardware",
  },
  {
    id: 11,
    code: "PROG-102",
    name: "Principles of Software Engineering",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "principles-of-software-engineering",
  },
  {
    id: 12,
    code: "PROG-103",
    name: "Principles of Structured Programming",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-2",
    slug: "principles-of-structured-programming",
  },

  // Year 2 Sem 1
  {
    id: 13,
    code: "DCOMP-114",
    name: "Database Systems",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "database-systems",
  },
  {
    id: 14,
    code: "COMM-231",
    name: "Communication in the New Economy",
    type: "Minor",
    credits: 2,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "communication-in-the-new-economy",
  },
  {
    id: 15,
    code: "PROG-211",
    name: "Object Oriented Programming Methods 1",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "object-oriented-programming-methods-1",
  },
  {
    id: 16,
    code: "DCOMP-204",
    name: "Web Design 1",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "web-design-1",
  },
  {
    id: 17,
    code: "DTECH-102",
    name: "Fundamentals of Computer Systems",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "fundamentals-of-computer-systems",
  },
  {
    id: 18,
    code: "MULT-302",
    name: "Multimedia Technology",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-3",
    slug: "multimedia-technology",
  },

  // Year 2 Sem 2
  {
    id: 19,
    code: "COMP-315",
    name: "Introduction to Information Systems",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "introduction-to-information-systems",
  },
  {
    id: 20,
    code: "PROG-315",
    name: "Object Oriented Programming Methods 2",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "object-oriented-programming-methods-2",
  },
  {
    id: 21,
    code: "MATH-303",
    name: "Probability & Statistics",
    type: "Minor",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "probability-statistics",
  },
  {
    id: 22,
    code: "MULT-315",
    name: "Multimedia Authoring",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "multimedia-authoring",
  },
  {
    id: 23,
    code: "DCOMP-322",
    name: "Networking Administration",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "networking-administration",
  },
  {
    id: 24,
    code: "TECH-307",
    name: "Mobile Commerce Systems",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-4",
    slug: "mobile-commerce-systems",
  },

  // Year 3 Sem 1
  {
    id: 25,
    code: "DCOMP-216",
    name: "E-Commerce Systems",
    type: "Minor",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "e-commerce-systems",
  },
  {
    id: 26,
    code: "DPROG-207",
    name: "Web Programming Techniques",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "web-programming-techniques",
  },
  {
    id: 27,
    code: "PROG-209",
    name: "Event Driven Programming",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "event-driven-programming",
  },
  {
    id: 28,
    code: "DTECH-206",
    name: "Human Computer Interaction",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "human-computer-interaction",
  },
  {
    id: 29,
    code: "DPROG-312",
    name: "Software Engineering & Development",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "software-engineering-development",
  },
  {
    id: 30,
    code: "DMULT-313",
    name: "3D Animation",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-5",
    slug: "3d-animation",
  },

  // Year 3 Sem 2
  {
    id: 31,
    code: "DCOMP-331",
    name: "Systems Administration & Management",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "systems-administration-management",
  },
  {
    id: 32,
    code: "COMP-320",
    name: "Management Information Systems",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "management-information-systems",
  },
  {
    id: 33,
    code: "DCOMP-318",
    name: "Data Communications & Networks",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "data-communications-networks",
  },
  {
    id: 34,
    code: "DPROG-316",
    name: "Distributed Systems",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "distributed-systems",
  },
  {
    id: 35,
    code: "DCOMP-205",
    name: "Operating Systems",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "operating-systems",
  },
  {
    id: 36,
    code: "DFINA-408",
    name: "Business Finance",
    type: "Minor",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-6",
    slug: "business-finance",
  },

  // Year 4 Sem 1
  {
    id: 37,
    code: "DPROJ-401",
    name: "Project Management",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "project-management",
  },
  {
    id: 38,
    code: "DFINA-405",
    name: "E-Business Management",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "e-business-management",
  },
  {
    id: 39,
    code: "DSYSE-406",
    name: "IT & Strategic Management",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "it-strategic-management",
  },
  {
    id: 40,
    code: "DCOMP-403",
    name: "Internet Security & Management",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "internet-security-management",
  },
  {
    id: 41,
    code: "DCOMP-404",
    name: "Network Security",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "network-security",
  },
  {
    id: 42,
    code: "DMULT-221",
    name: "Interactive Multimedia",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-7",
    slug: "interactive-multimedia",
  },

  // Year 4 Sem 2
  {
    id: 43,
    code: "DINTR-301",
    name: "Practical Internship",
    type: "Major",
    credits: 9,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-8",
    slug: "practical-internship",
  },
  {
    id: 44,
    code: "DINTR-302",
    name: "Internship Report",
    type: "Major",
    credits: 6,
    program: "Bachelor of Science (Hons) in Information Technology",
    programId: 1,
    programCode: "BIT",
    semester: "sem-8",
    slug: "internship-report",
  },

  // Year 1 Sem 1
  {
    id: 44,
    code: "SCM-1013",
    name: "Civic Education",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "civic-education",
  },
  {
    id: 45,
    code: "DFREN-224",
    name: "French Language 1",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "french-language-1",
  },
  {
    id: 46,
    code: "COMM-108",
    name: "Introduction to Communication & Study Skills",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "introduction-to-communication-study-skills",
  },
  {
    id: 47,
    code: "COMP-101",
    name: "Introduction to Computer Skills",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "introduction-to-computer-skills",
  },
  {
    id: 48,
    code: "CRET-101",
    name: "Creative & Innovation Studies",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "creative-innovation-studies",
  },
  {
    id: 49,
    code: "PROG-101",
    name: "Principles of Programming Logic & Design",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-1",
    slug: "principles-of-programming-logic-design",
  },

  // Year 1 Sem 2
  {
    id: 50,
    code: "MATH-108",
    name: "Computerized Mathematics",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "computerized-mathematics",
  },
  {
    id: 51,
    code: "PROG-103",
    name: "Principles of Structured Programming",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "principles-of-structured-programming",
  },
  {
    id: 52,
    code: "COMP-105",
    name: "Introduction to Data Communication",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "introduction-to-data-communication",
  },
  {
    id: 53,
    code: "COMP-109",
    name: "Introduction to Computer Hardware",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "introduction-to-computer-hardware",
  },
  {
    id: 54,
    code: "COMP-102",
    name: "Introduction to Databases",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "introduction-to-databases",
  },
  {
    id: 55,
    code: "PROG-102",
    name: "Principles of Software Engineering",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-2",
    slug: "principles-of-software-engineering",
  },

  // Year 2 Sem 1
  {
    id: 56,
    code: "COMP-217",
    name: "System Analysis & Design",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "system-analysis-design",
  },
  {
    id: 57,
    code: "PROG-211",
    name: "Object Oriented Programming Methods 1",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "object-oriented-programming-methods-1",
  },
  {
    id: 58,
    code: "COMP-315",
    name: "Introduction to Information Systems",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "introduction-to-information-systems",
  },
  {
    id: 59,
    code: "TECH-307",
    name: "Mobile Commerce Systems",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "mobile-commerce-systems",
  },
  {
    id: 60,
    code: "BUSSD-301",
    name: "Concepts of Strategic Management",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "concepts-of-strategic-management",
  },
  {
    id: 61,
    code: "DCOMP-114",
    name: "Database Systems",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-3",
    slug: "database-systems",
  },

  // Year 2 Sem 2
  {
    id: 62,
    code: "MKT-101",
    name: "Principles of Marketing",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-4",
    slug: "principles-of-marketing",
  },
  {
    id: 63,
    code: "LAW-204",
    name: "Business Law",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-4",
    slug: "business-law",
  },
  {
    id: 64,
    code: "COMP-218",
    name: "Information Systems Security",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-4",
    slug: "information-systems-security",
  },
  {
    id: 65,
    code: "DBUSS-205",
    name: "Fundamentals of Entrepreneurship",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-4",
    slug: "fundamentals-of-entrepreneurship",
  },
  {
    id: 66,
    code: "COMP-211",
    name: "E-Commerce Systems",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-4",
    slug: "e-commerce-systems",
  },

  // Year 3 Sem 1
  {
    id: 67,
    code: "DAMRT-211",
    name: "Strategic Marketing Management",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-5",
    slug: "strategic-marketing-management",
  },
  {
    id: 68,
    code: "DTECH-206",
    name: "Human-Computer Interaction",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-5",
    slug: "human-computer-interaction",
  },
  {
    id: 69,
    code: "DCOMP-218",
    name: "Data Communications & Networking",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-5",
    slug: "data-communications-networking",
  },
  {
    id: 70,
    code: "DPROG-207",
    name: "Web Programming Techniques",
    type: "Core",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-5",
    slug: "web-programming-techniques",
  },
  {
    id: 71,
    code: "DMGMT-305",
    name: "Human Resource Management",
    type: "Minor",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-5",
    slug: "human-resource-management",
  },

  // Year 3 Sem 2
  {
    id: 72,
    code: "BUSSD-202",
    name: "Business Planning",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-6",
    slug: "business-planning",
  },
  {
    id: 73,
    code: "COMP-318",
    name: "IT Project Management",
    type: "Minor",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-6",
    slug: "it-project-management",
  },
  {
    id: 74,
    code: "DMGMT-307",
    name: "Supply Chain Management",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-6",
    slug: "supply-chain-management",
  },
  {
    id: 75,
    code: "MAT-303",
    name: "Research Methodology",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-6",
    slug: "research-methodology",
  },
  {
    id: 76,
    code: "DCOMP-336",
    name: "Decision Support System",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-6",
    slug: "decision-support-system",
  },

  // Year 4 Sem 1
  {
    id: 77,
    code: "DCOMP-322",
    name: "Networking Administration",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "networking-administration",
  },
  {
    id: 78,
    code: "DPROJ-301",
    name: "Research Project",
    type: "Core",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "research-project",
  },
  {
    id: 79,
    code: "DCOMP-401",
    name: "Business Intelligence",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "business-intelligence",
  },
  {
    id: 80,
    code: "DMGMT-316",
    name: "Ethics & Professional Conduct",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "ethics-professional-conduct",
  },
  {
    id: 81,
    code: "DLAW-207",
    name: "I.T Intellectual Property Rights and Ethics",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "it-intellectual-property-rights-and-ethics",
  },
  {
    id: 82,
    code: "DMGMT-311",
    name: "Knowledge Management",
    type: "Major",
    credits: 3,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-7",
    slug: "knowledge-management",
  },

  // Year 4 Sem 2
  {
    id: 83,
    code: "DINTR-301",
    name: "Practical Internship",
    type: "Major",
    credits: 9,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-8",
    slug: "practical-internship",
  },
  {
    id: 84,
    code: "DPROJ-301",
    name: "Research Project",
    type: "Major",
    credits: 4,
    program: "Bachelor of Science (Hons) in Business Information Technology",
    programId: 2,
    programCode: "BBIT",
    semester: "sem-8",
    slug: "research-project",
  },
  // Year 1 Sem 1
  {
    id: 85,
    code: "SCM-1013",
    name: "Civic Education",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "civic-education",
  },
  {
    id: 86,
    code: "DFREN-224",
    name: "French Language 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "french-language-1",
  },
  {
    id: 87,
    code: "COMM-108",
    name: "Introduction to Communication & Study Skills",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "introduction-to-communication-study-skills",
  },
  {
    id: 88,
    code: "COMP-101",
    name: "Introduction to Computer Skills",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "introduction-to-computer-skills",
  },
  {
    id: 89,
    code: "CRET-101",
    name: "Creative & Innovation Studies",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "creative-innovation-studies",
  },
  {
    id: 90,
    code: "PROG-101",
    name: "Principles of Programming Logic & Design",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-1",
    slug: "principles-of-programming-logic-design",
  },

  // Year 1 Sem 2
  {
    id: 91,
    code: "MATH-108",
    name: "Computerized Mathematics",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "computerized-mathematics",
  },
  {
    id: 92,
    code: "PROG-102",
    name: "Principles of Software Engineering",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "principles-of-software-engineering",
  },
  {
    id: 93,
    code: "COMP-105",
    name: "Introduction to Data Communication",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "introduction-to-data-communication",
  },
  {
    id: 94,
    code: "COMP-102",
    name: "Introduction to Databases",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "introduction-to-databases",
  },
  {
    id: 95,
    code: "MULT-201",
    name: "Introduction to Multimedia",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "introduction-to-multimedia",
  },
  {
    id: 96,
    code: "",
    name: "Principles of Structured Programming",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-2",
    slug: "principles-of-structured-programming",
  },

  // Year 2 Sem 1
  {
    id: 97,
    code: "COMM-231",
    name: "Communication in the New Economy",
    type: "Minor",
    credits: 2,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "communication-in-the-new-economy",
  },
  {
    id: 98,
    code: "DCOMP-114",
    name: "Database Systems",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "database-systems",
  },
  {
    id: 99,
    code: "PROG-202",
    name: "Software Engineering",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "software-engineering",
  },
  {
    id: 100,
    code: "DPROG-211",
    name: "Object Oriented Programming Methods 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "object-oriented-programming-methods-1",
  },
  {
    id: 101,
    code: "DTECH-102",
    name: "Fundamentals of Computer Systems",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "fundamentals-of-computer-systems",
  },
  {
    id: 102,
    code: "MULT-111",
    name: "Introduction to Digital Imaging",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-3",
    slug: "introduction-to-digital-imaging",
  },

  // Year 2 Sem 2
  {
    id: 103,
    code: "PROG-315",
    name: "Object Oriented Programming Methods 2",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "object-oriented-programming-methods-2",
  },
  {
    id: 104,
    code: "SOUD-209",
    name: "Sound Production",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "sound-production",
  },
  {
    id: 105,
    code: "MATH-303",
    name: "Probability & Statistics",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "probability-statistics",
  },
  {
    id: 106,
    code: "MULT-315",
    name: "Multimedia Authoring",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "multimedia-authoring",
  },
  {
    id: 107,
    code: "DCOMP-204",
    name: "Web Design 1",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "web-design-1",
  },
  {
    id: 108,
    code: "VIDE-103",
    name: "Introduction to Video Technology",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-4",
    slug: "introduction-to-video-technology",
  },

  // Year 3 Sem 1
  {
    id: 109,
    code: "COMP-217",
    name: "System Analysis & Design",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "system-analysis-design",
  },
  {
    id: 110,
    code: "DCOMP-218",
    name: "Data Communications & Networking",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "data-communications-networking",
  },
  {
    id: 111,
    code: "DGRAP-101",
    name: "Computer Graphics 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "computer-graphics-1",
  },
  {
    id: 112,
    code: "DPROG-207",
    name: "Web Programming Techniques",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "web-programming-techniques",
  },
  {
    id: 113,
    code: "DTECH-206",
    name: "Human Computer Interaction",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "human-computer-interaction",
  },
  {
    id: 114,
    code: "DCOMP-320",
    name: "Data Structures and Algorithm Analysis",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-5",
    slug: "data-structures-algorithm-analysis",
  },

  // Year 3 Sem 2
  {
    id: 115,
    code: "DANIM-114",
    name: "Animation Studies 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "animation-studies-1",
  },
  {
    id: 116,
    code: "DMULT-221",
    name: "Interactive Multimedia",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "interactive-multimedia",
  },
  {
    id: 117,
    code: "MAT-303",
    name: "Research Methodology",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "research-methodology",
  },
  {
    id: 118,
    code: "COMP-318",
    name: "IT Project Management",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "it-project-management",
  },
  {
    id: 119,
    code: "DLAW-207",
    name: "I.T Intellectual property Rights and Ethics",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "it-intellectual-property-rights-ethics",
  },
  {
    id: 120,
    code: "DBUSS-205",
    name: "Fundamentals of Entrepreneurship",
    type: "Minor",
    credits: 2,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-6",
    slug: "fundamentals-of-entrepreneurship",
  },

  // Year 4 Sem 1
  {
    id: 121,
    code: "DCOMP-343",
    name: "Software Testing & Reliability",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-7",
    slug: "software-testing-reliability",
  },
  {
    id: 122,
    code: "DMULT-223",
    name: "Character Animation",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-7",
    slug: "character-animation",
  },
  {
    id: 123,
    code: "DTECH-307",
    name: "Virtual Reality",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-7",
    slug: "virtual-reality",
  },
  {
    id: 124,
    code: "DMULT-222",
    name: "Digital Production",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-7",
    slug: "digital-production",
  },
  {
    id: 125,
    code: "DPROJ-301",
    name: "Research Project",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-7",
    slug: "research-project",
  },

  // Year 4 Sem 2
  {
    id: 126,
    code: "DINTR-301",
    name: "Practical Internship",
    type: "Major",
    credits: 9,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-8",
    slug: "practical-internship",
  },
  {
    id: 127,
    code: "DINTR-302",
    name: "Internship Report",
    type: "Major",
    credits: 6,
    program:
      "Bachelor of Science (Hons) in Software Engineering with Multimedia",
    programId: 3,
    programCode: "BSEM",
    semester: "sem-8",
    slug: "internship-report",
  },
  // BICT Program
  {
    id: 128,
    code: "SCM-1013",
    name: "Civic Education",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "civic-education",
  },
  {
    id: 129,
    code: "DFREN-224",
    name: "French Language 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "french-language-1",
  },
  {
    id: 130,
    code: "COMM-108",
    name: "Introduction to Communication & Study Skills",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "introduction-to-communication-study-skills",
  },
  {
    id: 131,
    code: "COMP-101",
    name: "Introduction to Computer Skills",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "introduction-to-computer-skills",
  },
  {
    id: 132,
    code: "CRET-101",
    name: "Creative & Innovation Studies",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "creative-innovation-studies",
  },
  {
    id: 133,
    code: "PROG-101",
    name: "Principles of Programming Logic & Design",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-1",
    slug: "principles-of-programming-logic-design",
  },

  // Year 1 Sem 2
  {
    id: 134,
    code: "MATH-108",
    name: "Computerized Mathematics",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "computerized-mathematics",
  },
  {
    id: 135,
    code: "PROG-103",
    name: "Principles of Structured Programming",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "principles-of-structured-programming",
  },
  {
    id: 136,
    code: "COMP-105",
    name: "Introduction to Data Communication",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "introduction-to-data-communication",
  },
  {
    id: 137,
    code: "COMP-102",
    name: "Introduction to Databases",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "introduction-to-databases",
  },
  {
    id: 138,
    code: "COMP-109",
    name: "Introduction to Computer Hardware",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "introduction-to-computer-hardware",
  },
  {
    id: 139,
    code: "PROG-102",
    name: "Principles of Software Engineering",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-2",
    slug: "principles-of-software-engineering",
  },

  // Year 2 Sem 1
  {
    id: 140,
    code: "COMM-231",
    name: "Communication in the New Economy",
    type: "Minor",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-3",
    slug: "communication-in-the-new-economy",
  },
  {
    id: 141,
    code: "DPROG-104",
    name: "Object Oriented Programming Methods 1",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-3",
    slug: "object-oriented-programming-methods-1",
  },
  {
    id: 142,
    code: "DCOMP-337",
    name: "Database Design & Management 2",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-3",
    slug: "database-design-management-2",
  },
  {
    id: 143,
    code: "TECH-306",
    name: "Mobile System",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-3",
    slug: "mobile-system",
  },
  {
    id: 144,
    code: "DCOMP-320",
    name: "Data Structures and Algorithm Analysis",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-3",
    slug: "data-structures-algorithm-analysis",
  },

  // Year 2 Sem 2
  {
    id: 145,
    code: "BCT-8023",
    name: "LAN & High Speed Technology",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-4",
    slug: "lan-high-speed-technology",
  },
  {
    id: 146,
    code: "BUSS-305",
    name: "Entrepreneurship",
    type: "Minor",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-4",
    slug: "entrepreneurship",
  },
  {
    id: 147,
    code: "DPROG-208",
    name: "Object Oriented Programming Methods",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-4",
    slug: "object-oriented-programming-methods",
  },
  {
    id: 148,
    code: "DPROG-207",
    name: "Web Programming Techniques",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-4",
    slug: "web-programming-techniques",
  },
  {
    id: 149,
    code: "UCC-1032",
    name: "Public Speaking & Presentation Skills",
    type: "Core",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-4",
    slug: "public-speaking-presentation-skills",
  },

  // Year 3 Sem 1
  {
    id: 150,
    code: "MATH-307",
    name: "Discrete Structures",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "discrete-structures",
  },
  {
    id: 151,
    code: "COMP-217",
    name: "System Analysis & Design",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "system-analysis-design",
  },
  {
    id: 152,
    code: "DCOMP-205",
    name: "Wireless Networks and Applications",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "wireless-networks-applications",
  },
  {
    id: 153,
    code: "MATH-303",
    name: "Probability & Statistics",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "probability-statistics",
  },
  {
    id: 154,
    code: "TECH-105",
    name: "Wireless Internet Application",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "wireless-internet-application",
  },
  {
    id: 155,
    code: "MAT-303",
    name: "Research Methodology",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-5",
    slug: "research-methodology",
  },

  // Year 3 Sem 2
  {
    id: 156,
    code: "DLAW-207",
    name: "IT Intellectual Property Rights and Ethics",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-6",
    slug: "it-intellectual-property-rights-ethics",
  },
  {
    id: 157,
    code: "COMP-318",
    name: "IT Project Management",
    type: "Core",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-6",
    slug: "it-project-management",
  },
  {
    id: 158,
    code: "BCT-2033",
    name: "Client/Server Architecture",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-6",
    slug: "client-server-architecture",
  },
  {
    id: 159,
    code: "DCOMP-323",
    name: "Operating Systems",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-6",
    slug: "operating-systems",
  },
  {
    id: 160,
    code: "DPROJ-302",
    name: "Major Project 1",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-6",
    slug: "major-project-1",
  },

  // Year 4 Sem 1
  {
    id: 161,
    code: "MULT-302",
    name: "Multimedia Technology",
    type: "Major",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-7",
    slug: "multimedia-technology",
  },
  {
    id: 162,
    code: "DTECH-207",
    name: "Computer Maintenance & Upgrade",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-7",
    slug: "computer-maintenance-upgrade",
  },
  {
    id: 163,
    code: "DCOM-324",
    name: "Network Design and Management",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-7",
    slug: "network-design-management",
  },
  {
    id: 164,
    code: "DPROJ-301",
    name: "Research Project",
    type: "Major",
    credits: 4,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-7",
    slug: "research-project",
  },
  {
    id: 165,
    code: "DMGMT-311",
    name: "Knowledge Management",
    type: "Minor",
    credits: 3,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-7",
    slug: "knowledge-management",
  },

  // Year 4 Sem 2
  {
    id: 166,
    code: "DINTR-301",
    name: "Practical Internship",
    type: "Major",
    credits: 9,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-8",
    slug: "practical-internship",
  },
  {
    id: 167,
    code: "DINTR-302",
    name: "Internship Report",
    type: "Major",
    credits: 6,
    program:
      "Bachelor of Science (Hons) in Information & Communication Technology",
    programId: 4,
    programCode: "BICT",
    semester: "sem-8",
    slug: "internship-report",
  },
];

export const programs = [
  {
    id: 1,
    code: "BIT",
    name: "Bachelor of Science (Hons) in Information Technology",
    slug: "bachelor-of-science-hons-in-information-technology",
  },
  {
    id: 2,
    code: "BBIT",
    name: "Bachelor of Science (Hons) in Business Information Technology",
    slug: "bachelor-of-science-hons-in-business-information-technology",
  },
  {
    id: 3,
    code: "BSEM",
    name: "Bachelor of Science (Hons) in Software Engineering",
    slug: "bachelor-of-science-hons-in-software-engineering",
  },
  {
    id: 4,
    code: "BICT",
    name: "Bachelor of Science (Hons) in Information & Communication Technology",
    slug: "bachelor-of-science-hons-in-information-communication-technology",
  },
];
export const semesters = [
  { id: 1, name: "Semester 1", code: "sem-1" },
  { id: 2, name: "Semester 2", code: "sem-2" },
  { id: 3, name: "Semester 3", code: "sem-3" },
  { id: 4, name: "Semester 4", code: "sem-4" },
  { id: 5, name: "Semester 5", code: "sem-5" },
  { id: 6, name: "Semester 6", code: "sem-6" },
  { id: 7, name: "Semester 7", code: "sem-7" },
  { id: 8, name: "Semester 8", code: "sem-8" },
];
export const weeks = [
  { id: 1, name: "Week 1" },
  { id: 2, name: "Week 2" },
  { id: 3, name: "Week 3" },
  { id: 4, name: "Week 4" },
  { id: 5, name: "Week 5" },
  { id: 6, name: "Week 6" },
  { id: 7, name: "Week 7" },
  { id: 8, name: "Week 8" },
  { id: 10, name: "Week 9" },
  { id: 11, name: "Week 10" },
];
